version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"

  auth_service:
    build: .
    container_name: auth_service
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:password@mysql/auth_db
    ports:
      - "8000:8000"
